/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Frames;

import FiveCodMover.FiveCodMoverJFrame;
import Vista.Paneles.PanelControlAsig;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Diego
 */
public class frmAvanceActividades extends javax.swing.JFrame {

    /**
     * Creates new form frmAvanceActividades
     * @param a
     */
    public frmAvanceActividades(int[] a) {
        initComponents();
        this.setLocationRelativeTo(null);  
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        
        this.a = a;
        
        jTFFecha.setText(PanelControlAsig.fechaFin);
        jTFRealizadas.setText(String.valueOf(a[0]));
        jTFEnProceso.setText(String.valueOf(a[1]));
        jTFNoRealizadas.setText(String.valueOf(a[2]));
        
        jTFTotal.setText(String.valueOf(a[0]+a[1]+a[2]));
    }
    
    int[] a = new int[3];
    
    public frmAvanceActividades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelSuperior = new javax.swing.JPanel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jPanelTransparente2 = new LIB.JPanelTransparente();
        jLabel4 = new javax.swing.JLabel();
        jTFTotal = new javax.swing.JLabel();
        jTFFecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFNoRealizadas = new LIB.FSTexFieldMD();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTFEnProceso = new LIB.FSTexFieldMD();
        jLabel11 = new javax.swing.JLabel();
        jTFRealizadas = new LIB.FSTexFieldMD();
        btnGrafica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSuperior.setBackground(new java.awt.Color(33, 50, 66));
        PanelSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelSuperiorMouseDragged(evt);
            }
        });
        PanelSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelSuperiorMousePressed(evt);
            }
        });

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/Boton-Minimizar.png"))); // NOI18N

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/Boton-Cerrar.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(685, Short.MAX_VALUE)
                .addComponent(lblMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addGroup(PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCerrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(PanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, -1));

        jPanelTransparente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Actividades:");
        jPanelTransparente2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 70));

        jTFTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTFTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTFTotal.setText("jLabel12");
        jPanelTransparente2.add(jTFTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, 70));

        jTFFecha.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTFFecha.setForeground(new java.awt.Color(255, 255, 255));
        jTFFecha.setText("jLabel12");
        jPanelTransparente2.add(jTFFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, 70));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha de finalizacion:");
        jPanelTransparente2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 70));

        jPanel1.add(jPanelTransparente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 429, 720, -1));

        jTFNoRealizadas.setEditable(false);
        jTFNoRealizadas.setForeground(new java.awt.Color(0, 0, 0));
        jTFNoRealizadas.setBordeColorFocus(new java.awt.Color(51, 102, 0));
        jTFNoRealizadas.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        jTFNoRealizadas.setPlaceholder("");
        jPanel1.add(jTFNoRealizadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 160, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/IconRealizada.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/IconEnProceso.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, 30));

        jTFEnProceso.setEditable(false);
        jTFEnProceso.setForeground(new java.awt.Color(0, 0, 0));
        jTFEnProceso.setBordeColorFocus(new java.awt.Color(204, 255, 0));
        jTFEnProceso.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        jTFEnProceso.setPlaceholder("");
        jPanel1.add(jTFEnProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 160, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/IconNoRealizada.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 30, 30));

        jTFRealizadas.setEditable(false);
        jTFRealizadas.setForeground(new java.awt.Color(0, 0, 0));
        jTFRealizadas.setBordeColorFocus(new java.awt.Color(51, 153, 0));
        jTFRealizadas.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        jTFRealizadas.setPlaceholder("");
        jTFRealizadas.setSelectionColor(new java.awt.Color(0, 204, 0));
        jPanel1.add(jTFRealizadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 160, -1));

        btnGrafica.setBackground(new java.awt.Color(0, 51, 51));
        btnGrafica.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnGrafica.setForeground(new java.awt.Color(255, 255, 255));
        btnGrafica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/negocios-y-finanzas.png"))); // NOI18N
        btnGrafica.setText("Generar Grafico");
        btnGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void PanelSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSuperiorMouseDragged
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_PanelSuperiorMouseDragged

    private void PanelSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSuperiorMousePressed
        FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_PanelSuperiorMousePressed

    private void btnGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficaActionPerformed
        try
        {                 
            DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
            dtsc.setValue(a[0], "Actividades Realizadas","");
            dtsc.setValue(a[1], "Actividades en proceso","");
            dtsc.setValue(a[2], "Actividades no realizadas","");
            JFreeChart ch = ChartFactory.createBarChart3D("", "", "", dtsc,PlotOrientation.HORIZONTAL, true, true, false);
            ChartPanel cp = new ChartPanel(ch);
            add(cp);
            cp.setBounds(5,100,745,245);
        }
        catch(NumberFormatException e)
        {
            new frmAlerta("Error al cargar la grafica",3).setVisible(true);
            System.out.println(e);
        }
    }//GEN-LAST:event_btnGraficaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAvanceActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAvanceActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAvanceActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAvanceActividades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAvanceActividades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JButton btnGrafica;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private LIB.JPanelTransparente jPanelTransparente2;
    public static LIB.FSTexFieldMD jTFEnProceso;
    public static javax.swing.JLabel jTFFecha;
    public static LIB.FSTexFieldMD jTFNoRealizadas;
    public static LIB.FSTexFieldMD jTFRealizadas;
    public static javax.swing.JLabel jTFTotal;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblMinimizar;
    // End of variables declaration//GEN-END:variables
}
