/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Frames;

import Clases.ClassFuncionesSQL;
import FiveCodMover.FiveCodMoverJFrame;
import java.awt.Color;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Diego
 */
public class frmRecuperacion extends javax.swing.JFrame {

    /**
     * Creates new form frmRecuperacion
     */
    public frmRecuperacion() {
        initComponents();
        this.setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTFCorreo = new LIB.FSTexFieldMD();
        lblCampo1 = new javax.swing.JLabel();
        jTFUsuario = new LIB.FSTexFieldMD();
        lblCampo2 = new javax.swing.JLabel();
        btnIngresar = new LIB.FSButtonMD();
        jLabel1 = new javax.swing.JLabel();
        btnValidar = new LIB.FSButtonMD();
        btnEstadoCorreo = new LIB.FSButtonMD();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(50, 75, 94));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFCorreo.setEditable(false);
        jTFCorreo.setForeground(new java.awt.Color(0, 0, 0));
        jTFCorreo.setBordeColorFocus(new java.awt.Color(0, 51, 51));
        jTFCorreo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 15)); // NOI18N
        jTFCorreo.setPlaceholder("");
        jTFCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCorreoKeyTyped(evt);
            }
        });
        jPanel1.add(jTFCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 269, 40));

        lblCampo1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 17)); // NOI18N
        lblCampo1.setForeground(new java.awt.Color(255, 255, 255));
        lblCampo1.setText("Correo");
        jPanel1.add(lblCampo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 50));

        jTFUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jTFUsuario.setBordeColorFocus(new java.awt.Color(0, 51, 51));
        jTFUsuario.setFont(new java.awt.Font("Segoe UI Emoji", 1, 15)); // NOI18N
        jTFUsuario.setPlaceholder("");
        jTFUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(jTFUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 269, 40));

        lblCampo2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 17)); // NOI18N
        lblCampo2.setForeground(new java.awt.Color(255, 255, 255));
        lblCampo2.setText("Ingrese su usuario");
        jPanel1.add(lblCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 50));

        btnIngresar.setBackground(new java.awt.Color(50, 75, 94));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/Icono_Anterior.png"))); // NOI18N
        btnIngresar.setText("  Regresar al login");
        btnIngresar.setColorHover(new java.awt.Color(18, 31, 43));
        btnIngresar.setColorNormal(new java.awt.Color(50, 75, 94));
        btnIngresar.setColorPressed(new java.awt.Color(18, 31, 43));
        btnIngresar.setColorTextHover(new java.awt.Color(255, 255, 255));
        btnIngresar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 17)); // NOI18N
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 320, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        jLabel1.setText(".");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 10, 30));

        btnValidar.setBackground(new java.awt.Color(50, 75, 94));
        btnValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/Icon_Validar.png"))); // NOI18N
        btnValidar.setColorHover(new java.awt.Color(50, 75, 94));
        btnValidar.setColorNormal(new java.awt.Color(50, 75, 94));
        btnValidar.setColorPressed(new java.awt.Color(50, 75, 94));
        btnValidar.setColorTextHover(new java.awt.Color(255, 255, 255));
        btnValidar.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });
        jPanel1.add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 40, -1));

        btnEstadoCorreo.setBackground(new java.awt.Color(50, 75, 94));
        btnEstadoCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/IconCorreoBloqueado.png"))); // NOI18N
        btnEstadoCorreo.setColorHover(new java.awt.Color(50, 75, 94));
        btnEstadoCorreo.setColorNormal(new java.awt.Color(50, 75, 94));
        btnEstadoCorreo.setColorPressed(new java.awt.Color(50, 75, 94));
        btnEstadoCorreo.setColorTextHover(new java.awt.Color(255, 255, 255));
        btnEstadoCorreo.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        btnEstadoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstadoCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCorreoKeyTyped

    }//GEN-LAST:event_jTFCorreoKeyTyped

    private void jTFUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuarioKeyTyped
    
    ClassFuncionesSQL sql = new ClassFuncionesSQL();
    
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_jPanel1MousePressed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        frmLogin c = new frmLogin();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        if (jTFUsuario.getText().trim().isEmpty()) 
        {
            new frmAlerta("Complete el campo usuario",2).setVisible(true);
        }
        else
        {
            String resultado = sql.obtenerCorreo(jTFUsuario.getText());
            if (!"".equals(resultado)) 
            {
                jTFCorreo.setText(resultado);
                btnEstadoCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/IconCorreoDesbloqueado.png")));
            }
            else
            {
                new frmAlerta("El usuario no tiene correo WTF",3).setVisible(true);
            }
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnEstadoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoCorreoActionPerformed
        if (!jTFCorreo.getText().trim().isEmpty()) 
        {
            Random r = new Random();
            int codigo = r.nextInt()*8999+1000;
            if (sql.enviarCorreo("<p>Hola solicitaste recuperar tu contraseña por medio de correo electronico <br>tu codigo de recuperacion es <b>'"+codigo+"'</b></p>","PROBUILDER COMPANY: Recuperacion de correo electronico", jTFCorreo.getText())) 
            {
                frmValidarCodigo c = new frmValidarCodigo(codigo,jTFUsuario.getText());
                c.setVisible(true);
                this.dispose();
            }
            else
            {
                new frmAlerta("Error al enviar el correo de recuperacion",3).setVisible(true);;
            }
        }
        else
        {
            new frmAlerta("Primero debe verificar su usuario",2).setVisible(true);
        }
    }//GEN-LAST:event_btnEstadoCorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRecuperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRecuperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRecuperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRecuperacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRecuperacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private LIB.FSButtonMD btnEstadoCorreo;
    private LIB.FSButtonMD btnIngresar;
    private LIB.FSButtonMD btnValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private LIB.FSTexFieldMD jTFCorreo;
    private LIB.FSTexFieldMD jTFUsuario;
    private javax.swing.JLabel lblCampo1;
    private javax.swing.JLabel lblCampo2;
    // End of variables declaration//GEN-END:variables
}
