/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.PreLogin;

/** Formulario de finalizacion de configuracion inicial
 *@since 11/07/2020
 * @author Diego Castro
 * @version 1.0
 */
public class PnlPrimerFinalizar extends javax.swing.JPanel {

    /**
     * Creates new form PrimerUsoFinalizar
     */
    public PnlPrimerFinalizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTexto1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTexto1.setText("Has finalizado la configuracion inicial");
        add(lblTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        lblTexto2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTexto2.setText("Ya puedes utilizar el sistema");
        add(lblTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/Icono_Log.JPG"))); // NOI18N
        add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    // End of variables declaration//GEN-END:variables
}
