/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Frames;

import FiveCodMover.FiveCodMoverJFrame;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Diego
 */
public class frmCostoProyecto extends javax.swing.JFrame {

    /**
     * Creates new form frmTotalesPresupuesto
     * @param o
     */
    public frmCostoProyecto(String[] o) {
        initComponents();
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        this.setLocationRelativeTo(null);
        try
        {
            jTFPreliminares.setText(o[0]);
            jTFManoObra.setText(o[1]);
            jTFMateriales.setText(o[2]);               
            jTFSubtotal.setText(o[3]);
            jTFImpuestos.setText(o[4]);
            jTFTotal.setText(o[5]);
        }
        catch(Exception e){System.out.print(e);}
    }
    
    public frmCostoProyecto(){}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelSuperior = new javax.swing.JPanel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        jTFPreliminares = new LIB.FSTexFieldMD();
        jLabel8 = new javax.swing.JLabel();
        jTFMateriales = new LIB.FSTexFieldMD();
        jLabel5 = new javax.swing.JLabel();
        jTFManoObra = new LIB.FSTexFieldMD();
        jLabel6 = new javax.swing.JLabel();
        jPanelTransparente2 = new LIB.JPanelTransparente();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFSubtotal = new javax.swing.JLabel();
        jTFTotal = new javax.swing.JLabel();
        jTFImpuestos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGrafica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        PanelSuperior.setBackground(new java.awt.Color(33, 50, 66));
        PanelSuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelSuperiorMouseDragged(evt);
            }
        });
        PanelSuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelSuperiorMousePressed(evt);
            }
        });

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/Boton-Minimizar.png"))); // NOI18N

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/Boton-Cerrar.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(653, Short.MAX_VALUE)
                .addComponent(lblMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addGroup(PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblMinimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCerrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTFPreliminares.setEditable(false);
        jTFPreliminares.setForeground(new java.awt.Color(0, 0, 0));
        jTFPreliminares.setBordeColorFocus(new java.awt.Color(0, 0, 102));
        jTFPreliminares.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        jTFPreliminares.setPlaceholder("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/IconMiniPreliminares.png"))); // NOI18N

        jTFMateriales.setEditable(false);
        jTFMateriales.setForeground(new java.awt.Color(0, 0, 0));
        jTFMateriales.setBordeColorFocus(new java.awt.Color(204, 255, 0));
        jTFMateriales.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        jTFMateriales.setPlaceholder("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/IconMIniMateriales.png"))); // NOI18N

        jTFManoObra.setEditable(false);
        jTFManoObra.setForeground(new java.awt.Color(0, 0, 0));
        jTFManoObra.setBordeColorFocus(new java.awt.Color(51, 102, 0));
        jTFManoObra.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        jTFManoObra.setPlaceholder("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/IconMiniManoObra.png"))); // NOI18N

        jPanelTransparente2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total :");
        jPanelTransparente2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subtotal :");
        jPanelTransparente2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 60));

        jTFSubtotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTFSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        jTFSubtotal.setText("jLabel12");
        jPanelTransparente2.add(jTFSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, 60));

        jTFTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTFTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTFTotal.setText("jLabel12");
        jPanelTransparente2.add(jTFTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, 60));

        jTFImpuestos.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTFImpuestos.setForeground(new java.awt.Color(255, 255, 255));
        jTFImpuestos.setText("jLabel12");
        jPanelTransparente2.add(jTFImpuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Impuestos :");
        jPanelTransparente2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Impuestos :");

        btnGrafica.setBackground(new java.awt.Color(0, 51, 51));
        btnGrafica.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnGrafica.setForeground(new java.awt.Color(255, 255, 255));
        btnGrafica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconografia/negocios-y-finanzas.png"))); // NOI18N
        btnGrafica.setText("Generar Grafico");
        btnGrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTFManoObra, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTFMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFPreliminares, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanelTransparente2, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(249, 249, 249)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel6))
                    .addComponent(jTFManoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel5))
                    .addComponent(jTFMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTFPreliminares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jPanelTransparente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void PanelSuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSuperiorMouseDragged
        FiveCodMoverJFrame.MouseDraggedFrame(evt, this);
    }//GEN-LAST:event_PanelSuperiorMouseDragged

    private void PanelSuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSuperiorMousePressed
        FiveCodMoverJFrame.MousePressed(evt);
    }//GEN-LAST:event_PanelSuperiorMousePressed

    private void btnGraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficaActionPerformed
        generarGrafico();
    }//GEN-LAST:event_btnGraficaActionPerformed

    /**
     * Metodo para generar el grafico con los totales de las areas del presupuesto utilizando los valores de los jtextfields
     */
    private void generarGrafico()
    {
        try
        {
            int manoObra = 0;
            int gastoMaterial = 0; 
            int gastosPreliminares = 0;
            String datos[] = new String[3];
            if (!jTFManoObra.getText().equals("$0") || !jTFMateriales.getText().equals("$0") || !jTFPreliminares.getText().equals("$0")) 
            {
                if (jTFMateriales.getText().contains(".") || jTFManoObra.getText().contains(".") || jTFPreliminares.getText().contains(".")) 
                {                   
                    datos[0] = jTFManoObra.getText();
                    datos[1] = jTFMateriales.getText();
                    datos[2] = jTFPreliminares.getText();
                    
                    for (int i = 0; i < datos.length; i++) 
                    {
                        String numeroEntero = "";
                        for (int j = 0; j < datos[i].length(); j++) 
                        {
                            boolean continuar = true;
                            if (datos[i].charAt(j) == '.')
                            {
                                continuar = false;
                            }
                            if (continuar) 
                            {
                                numeroEntero = numeroEntero + datos[i].charAt(j);
                            }
                        }
                        datos[i] = numeroEntero;
                    }
                }
                
                manoObra = Integer.parseInt(datos[0].replaceAll(",", "").replace("$", ""));
                gastoMaterial = Integer.parseInt(datos[1].replaceAll(",", "").replace("$", ""));
                gastosPreliminares = Integer.parseInt(datos[2].replaceAll(",", "").replace("$", ""));
            }
            DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
            dtsc.setValue(gastoMaterial, "Gasto de materiales","");
            dtsc.setValue(manoObra, "Gasto Mano de obra","");
            dtsc.setValue(gastosPreliminares, "Gastos Preliminares","");
            JFreeChart ch = ChartFactory.createBarChart3D("", "", "", dtsc,PlotOrientation.HORIZONTAL, true, true, false);
            ChartPanel cp = new ChartPanel(ch);
            add(cp);
            cp.setBounds(5,120,715,250);
        }
        catch(NumberFormatException e)
        {
            new frmAlerta("Error al cargar la grafica",3).setVisible(true);
            System.out.println(e);
        }
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCostoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCostoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCostoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCostoProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCostoProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JButton btnGrafica;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private LIB.JPanelTransparente jPanelTransparente2;
    public static javax.swing.JLabel jTFImpuestos;
    public static LIB.FSTexFieldMD jTFManoObra;
    public static LIB.FSTexFieldMD jTFMateriales;
    public static LIB.FSTexFieldMD jTFPreliminares;
    public static javax.swing.JLabel jTFSubtotal;
    public static javax.swing.JLabel jTFTotal;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblMinimizar;
    // End of variables declaration//GEN-END:variables
}
